version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "sapiensdb"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: ./backend  
    depends_on:
      - postgres
      - redis

  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery
    environment:
      DB_NAME: "sapiensdb"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./backend/
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      
