version: "3.8"

services:
  postgresdb:
    image: postgres:12
    container_name: sapienslink_postgres
    environment:
      POSTGRES_DB: sapiensdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # TODO: Hide PgAdmin credentials
  pgadmin:
    image: dpage/pgadmin4
    container_name: sapienslink_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - postgresdb

  django:
    container_name: sapienslink_django
    image: sapienslink/images:django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - static_volume/static/images:/app/static/images
      - media_volume:/app/mediafiles
    ports:
      - "8001:8000"
    depends_on:
      - postgresdb


  redis:
    container_name: sapienslink_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    container_name: sapienslink_celery_worker
    image: sapienslink/images:celery
    command: celery -A sapiensLink worker --loglevel=info
    depends_on:
      - django
      - redis

  celery_beat:
    container_name: sapienslink_celery_beat
    image: sapienslink/images:celery
    command: celery -A sapiensLink beat --loglevel=info
    depends_on:
      - django
      - redis

  nextjs:
    image: sapienslink/images:nextjs
    container_name: sapienslink_nextjs
    ports:
      - 3001:3000
    depends_on:
      - django

  nginx:
    image: sapienslink/images:nginx
    container_name: sapienslink_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - static_volume/static/images:/app/staticfiles/images
      - media_volume:/app/mediafiles
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - django
      - nextjs

  certbot:
    image: certbot/certbot:v2.9.0
    container_name: sapienslink_certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw


volumes:
  postgres_data:
  static_volume:
  media_volume:
