version: '3.8'

services:
  postgresdb:
    image: postgres:12
    container_name: sapienslink_postgresdb_1
    environment:
      POSTGRES_DB: "sapiensdb"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # TODO: Hide PgAdmin credentials
  pgadmin:
    image: dpage/pgadmin4
    container_name: sapienslink_pgadmin_1
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - postgresdb

  django:
    container_name: sapienslink_django_1
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8001:8000"
    depends_on:
      - postgresdb

  redis:
    container_name: sapienslink_redis_1
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    container_name: sapienslink_celery_worker_1
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    command: celery -A sapiensLink worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  celery_beat:
    container_name: sapienslink_celery_beat_1
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    command: celery -A sapiensLink beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  # Next.js frontend supporting SSR
  nextjs:
    container_name: sapienslink_nextjs_1
    image: node:lts
    ports:
      - 3001:3000
    depends_on:
      - django
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    # This will automatically build the frontend in production
    # more and serve the application in development mode
    command: sh -c 'npm install && npm run build_and_start'

  nginx:
    container_name: sapienslink_nginx_1
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - django
      - nextjs

volumes:
  postgres_data:
  static_volume:
  media_volume:
