version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: sapienslink_postgres_1
    environment:
      POSTGRES_DB: "sapiensdb"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  celery:
    container_name: sapienslink_celery_1
    build: ./backend  
    depends_on:
      - postgres
      - redis

  backend:
    build: ./backend 
    ports:
      - 8001:8000
    depends_on:
      - postgres
      - redis
      - celery
    environment:
      DB_NAME: "sapiensdb"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  # Next.js frontend supporting SSR
  frontend:
    image: node:lts
    ports:
      - 3001:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    # This will automatically build the frontend in production
    # more and serve the application in development mode
    command: sh -c 'npm run build_and_start'

  nginx:
    container_name: sapienslink_nginx_1
    build:
      context: ./backend/
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    - frontend
