# Dockerfile for Celery
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0

WORKDIR /app

# Install only the necessary dependencies for Celery
COPY requirements-celery.txt /app/
RUN pip install --no-cache-dir -r requirements-celery.txt

COPY . /app/
