# Dockerfile for Celery
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install only the necessary dependencies for Celery
COPY requirements-celery.txt /app/
RUN pip install --no-cache-dir -r requirements-celery.txt

COPY . /app/
