FROM nginx:alpine

ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT}

COPY ./backend/nginx.$ENVIRONMENT.conf /etc/nginx/conf.d/default.conf
ADD ./backend/static/images /app/staticfiles/images
ADD ./frontend/public /app/nextjs/public