export const topics = [
    { label: "Technology", value: "technology" },
    { label: "Science", value: "science" },
    { label: "Health & Wellness", value: "health_wellness" },
    { label: "Business & Entrepreneurship", value: "business_entrepreneurship" },
    { label: "Arts & Entertainment", value: "arts_entertainment" },
    { label: "Education", value: "education" },
    { label: "Lifestyle", value: "lifestyle" },
    { label: "Travel & Adventure", value: "travel_adventure" },
    { label: "Food & Cooking", value: "food_cooking" },
    { label: "Fashion & Beauty", value: "fashion_beauty" },
    { label: "Sports & Fitness", value: "sports_fitness" },
    { label: "Literature & Writing", value: "literature_writing" },
    { label: "History & Culture", value: "history_culture" },
    { label: "Environment & Sustainability", value: "environment_sustainability" },
    { label: "Politics & Current Events", value: "politics_current_events" },
    { label: "Personal Development", value: "personal_development" },
    { label: "Parenting & Family", value: "parenting_family" },
    { label: "Relationships & Dating", value: "relationships_dating" },
    { label: "Self-Care & Mental Health", value: "self_care_mental_health" },
    { label: "DIY & Crafts", value: "diy_crafts" },
    { label: "Finance & Investment", value: "finance_investment" },
    { label: "Gaming", value: "gaming" },
    { label: "Religion & Spirituality", value: "religion_spirituality" },
    { label: "Pets & Animals", value: "pets_animals" },
    { label: "Photography", value: "photography" },
    { label: "Career & Work", value: "career_work" },
    { label: "Motivation & Inspiration", value: "motivation_inspiration" },
    { label: "Gardening", value: "gardening" },
    { label: "Home Decor & Design", value: "home_decor_design" },
    { label: "Automotive & Vehicles", value: "automotive_vehicles" }
];
