name: Docker Image CI

on:
  push:
    branches: [ "dnl/deploy-on-vm" ]

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
